name: ECR push test

on:
  workflow_dispatch:

jobs:
  docker_push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ECR_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Pull, tag and push
        run: |
          docker pull memcached
          docker tag memcached:latest ${{ steps.login-ecr.outputs.registry }}/pipeline-repo:${{ github.run_id }}
          docker push ${{ steps.login-ecr.outputs.registry }}/pipeline-repo:${{ github.run_id }}