name: ECR push test

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Pull, tag and push
        run: |
          docker pull hello-world
          docker tag hello-world:latest ${{ steps.login-ecr.outputs.registry }}/pipeline-repo:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/pipeline-repo:latest