name: Terraform GitHub Pipeline
on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Project'
        required: true
      action:
        description: 'Action'
        required: true
        default: 'plan'
      branch:
        description: 'Branch'
        required: true
        default: 'main'
jobs:
  terraform:
    name: 'Terraform action'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.0
          terraform_wrapper: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/projects/${{ github.event.inputs.project }}

      - name: Terraform Plan
        if: ${{ github.event.inputs.action == 'plan' }}
        run: terraform plan -var="gcr_user=${{ env.gcr_user }}" -out tf.plan
        working-directory: terraform/projects/${{ github.event.inputs.project }}


      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        run: terraform apply -var="gcr_user=${{ env.gcr_user }}" -auto-approve
        working-directory: terraform/projects/${{ github.event.inputs.project }}